export const revenueData = [
    {
        "Product_ID": 372,
        "Product_Name": "Infusion Pump",
        "Lead_time_in_Days": 13,
        "Lead_time_in_Days_New": 13,
        "Avarage_Monthly_Sales": 41510,
        "Avg_Monthly_Sales_New": 34253,
        "Predicted_monthly_sales": 23890,
        "Predicted_monthly_sales_New": 23951,
        "Avarage_daily_sales": 796,
        "Avarage_daily_sales_New": 798,
        "Safety_Stock_For_15_Days": 7740,
        "Safety_Stock_For_15_Days_New": 7350,
        "Reorder_Point_Quantity": 18088,
        "Reorder_Point_Quantity_New": 17724
    },
    {
        "Product_ID": 800,
        "Product_Name": "Infusion Pump",
        "Lead_time_in_Days": 13,
        "Lead_time_in_Days_New": 13,
        "Avarage_Monthly_Sales": 35895,
        "Avg_Monthly_Sales_New": 18288,
        "Predicted_monthly_sales": 25684,
        "Predicted_monthly_sales_New": 33467,
        "Avarage_daily_sales": 856,
        "Avarage_daily_sales_New": 1116,
        "Safety_Stock_For_15_Days": 12000,
        "Safety_Stock_For_15_Days_New": 38700,
        "Reorder_Point_Quantity": 23128,
        "Reorder_Point_Quantity_New": 53208
    },
    {
        "Product_ID": 582,
        "Product_Name": "MRI Machine",
        "Lead_time_in_Days": 11,
        "Lead_time_in_Days_New": 11,
        "Avarage_Monthly_Sales": 20791,
        "Avg_Monthly_Sales_New": 41209,
        "Predicted_monthly_sales": 25684,
        "Predicted_monthly_sales_New": 30955,
        "Avarage_daily_sales": 856,
        "Avarage_daily_sales_New": 1032,
        "Safety_Stock_For_15_Days": 37680,
        "Safety_Stock_For_15_Days_New": 8640,
        "Reorder_Point_Quantity": 47096,
        "Reorder_Point_Quantity_New": 19992
    },
    {
        "Product_ID": 670,
        "Product_Name": "ECG Machine",
        "Lead_time_in_Days": 12,
        "Lead_time_in_Days_New": 12,
        "Avarage_Monthly_Sales": 4321,
        "Avg_Monthly_Sales_New": 32210,
        "Predicted_monthly_sales": 16777,
        "Predicted_monthly_sales_New": 23099,
        "Avarage_daily_sales": 559,
        "Avarage_daily_sales_New": 770,
        "Safety_Stock_For_15_Days": 22035,
        "Safety_Stock_For_15_Days_New": 15945,
        "Reorder_Point_Quantity": 28743,
        "Reorder_Point_Quantity_New": 25185
    },
    {
        "Product_ID": 773,
        "Product_Name": "MRI Machine",
        "Lead_time_in_Days": 14,
        "Lead_time_in_Days_New": 14,
        "Avarage_Monthly_Sales": 42159,
        "Avg_Monthly_Sales_New": 3585,
        "Predicted_monthly_sales": 25542,
        "Predicted_monthly_sales_New": 28117,
        "Avarage_daily_sales": 851,
        "Avarage_daily_sales_New": 937,
        "Safety_Stock_For_15_Days": 11640,
        "Safety_Stock_For_15_Days_New": 6420,
        "Reorder_Point_Quantity": 23554,
        "Reorder_Point_Quantity_New": 19538
    },
    {
        "Product_ID": 779,
        "Product_Name": "X-Ray Machine",
        "Lead_time_in_Days": 15,
        "Lead_time_in_Days_New": 15,
        "Avarage_Monthly_Sales": 45805,
        "Avg_Monthly_Sales_New": 3585,
        "Predicted_monthly_sales": 22926,
        "Predicted_monthly_sales_New": 14414,
        "Avarage_daily_sales": 764,
        "Avarage_daily_sales_New": 480,
        "Safety_Stock_For_15_Days": 53220,
        "Safety_Stock_For_15_Days_New": 117120,
        "Reorder_Point_Quantity": 64680,
        "Reorder_Point_Quantity_New": 124320
    },
    {
        "Product_ID": 567,
        "Product_Name": "Defibrillator",
        "Lead_time_in_Days": 11,
        "Lead_time_in_Days_New": 11,
        "Avarage_Monthly_Sales": 42851,
        "Avg_Monthly_Sales_New": 32210,
        "Predicted_monthly_sales": 23890,
        "Predicted_monthly_sales_New": 30090,
        "Avarage_daily_sales": 796,
        "Avarage_daily_sales_New": 1003,
        "Safety_Stock_For_15_Days": 31620,
        "Safety_Stock_For_15_Days_New": 2535,
        "Reorder_Point_Quantity": 40376,
        "Reorder_Point_Quantity_New": 13568
    },
    {
        "Product_ID": 663,
        "Product_Name": "X-Ray Machine",
        "Lead_time_in_Days": 14,
        "Lead_time_in_Days_New": 14,
        "Avarage_Monthly_Sales": 8176,
        "Avg_Monthly_Sales_New": 6888,
        "Predicted_monthly_sales": 24649,
        "Predicted_monthly_sales_New": 6600,
        "Avarage_daily_sales": 822,
        "Avarage_daily_sales_New": 220,
        "Safety_Stock_For_15_Days": 54855,
        "Safety_Stock_For_15_Days_New": 181275,
        "Reorder_Point_Quantity": 66363,
        "Reorder_Point_Quantity_New": 184355
    },
    {
        "Product_ID": 544,
        "Product_Name": "Surgical Instruments",
        "Lead_time_in_Days": 13,
        "Lead_time_in_Days_New": 13,
        "Avarage_Monthly_Sales": 37075,
        "Avg_Monthly_Sales_New": 49837,
        "Predicted_monthly_sales": 27147,
        "Predicted_monthly_sales_New": 33467,
        "Avarage_daily_sales": 905,
        "Avarage_daily_sales_New": 1116,
        "Safety_Stock_For_15_Days": 15465,
        "Safety_Stock_For_15_Days_New": 25680,
        "Reorder_Point_Quantity": 27230,
        "Reorder_Point_Quantity_New": 40188
    },
    {
        "Product_ID": 811,
        "Product_Name": "ECG Machine",
        "Lead_time_in_Days": 8,
        "Lead_time_in_Days_New": 8,
        "Avarage_Monthly_Sales": 16635,
        "Avg_Monthly_Sales_New": 17772,
        "Predicted_monthly_sales": 25824,
        "Predicted_monthly_sales_New": 31792,
        "Avarage_daily_sales": 861,
        "Avarage_daily_sales_New": 1060,
        "Safety_Stock_For_15_Days": 37260,
        "Safety_Stock_For_15_Days_New": 13380,
        "Reorder_Point_Quantity": 44148,
        "Reorder_Point_Quantity_New": 21860
    },
    {
        "Product_ID": 311,
        "Product_Name": "Stethoscope",
        "Lead_time_in_Days": 12,
        "Lead_time_in_Days_New": 12,
        "Avarage_Monthly_Sales": 35554,
        "Avg_Monthly_Sales_New": 34253,
        "Predicted_monthly_sales": 23890,
        "Predicted_monthly_sales_New": 18648,
        "Avarage_daily_sales": 796,
        "Avarage_daily_sales_New": 622,
        "Safety_Stock_For_15_Days": 8040,
        "Safety_Stock_For_15_Days_New": 39360,
        "Reorder_Point_Quantity": 17592,
        "Reorder_Point_Quantity_New": 46824
    },
    {
        "Product_ID": 332,
        "Product_Name": "X-Ray Machine",
        "Lead_time_in_Days": 8,
        "Lead_time_in_Days_New": 8,
        "Avarage_Monthly_Sales": 16282,
        "Avg_Monthly_Sales_New": 12631,
        "Predicted_monthly_sales": 20896,
        "Predicted_monthly_sales_New": 20833,
        "Avarage_daily_sales": 697,
        "Avarage_daily_sales_New": 694,
        "Safety_Stock_For_15_Days": 56940,
        "Safety_Stock_For_15_Days_New": 57300,
        "Reorder_Point_Quantity": 62516,
        "Reorder_Point_Quantity_New": 62852
    }
]